#! /bin/bash -uex

export ITM_HTM_RESTARTS=1 

#| sed 's/^\(.*\)::\(.*\)/\2:\1/g
OUT="results_$(date +"%T" | sed 's/:/_/g')"
ALGOS="rh_htm_gl_wt none locks"
REPS=3
#RNUM=10000000 #will get x 10 in database. with 3Mx10ops, expect lowest time be ~900ms longest 15s.

ITM_DEFAULT_METHOD=htm

for rep in $(seq $REPS); do
for algo in $ALGOS; do
    THREADS=16 #reset after every algo to default
    
    if [[ $algo == locks ]]; then
	make clean && make -j16 METHOD=locks
    elif [[ $algo == none ]]; then
	make clean && make -j16 METHOD=none
	THREADS=1 # correct thread number
    else
	make clean && make -j16 METHOD=tm
	export ITM_DEFAULT_METHOD=$algo 
    fi
    
    ./tmenv ./kccachetest sanity $THREADS 10000
    

    for thds in $(seq $THREADS); do 
    	for rep in $(seq $REPS); do
	    (taskset -c 0-7 \
		./tmenv \
		ocperf.py stat -x:: -e tx_mem.abort_capacity_write -e tx_mem.abort_conflict "-e tx_exec.misc"{1,2,3,4,5} -e rtm_retired.start -e rtm_retired.commit -e rtm_retired.aborted:pp "-e rtm_retired.aborted_misc"{1,2,3,4,5} \
		./kccachetest bench -th $thds -targetcnt 1000000 -readpcnt 90 -durations 2 2>&1;
		echo 'algo:' $algo) >> $OUT
	done
    done 
done
