#! /bin/bash -uex

export ITM_HTM_RESTARTS=1 

#| sed 's/^\(.*\)::\(.*\)/\2:\1/g
OUT="results.cat"
ALGOS="htm rh_htm_gl_wt none locks"
REPS=3
RNUM=10000000 #will get x 10 in database. with 3Mx10ops, expect lowest time be ~900ms longest 15s.

for algo in $ALGOS; do

    if [[ $algo == locks ]]; then
	make clean && make -j16 METHOD=locks
	THREADS=8
    elif [[ $algo == none ]]; then
	make clean && make -j16 METHOD=locks
	THREADS=1
    else
	make clean && make -j8 METHOD=tm
	export ITM_DEFAULT_METHOD=$algo 
	THREADS=8
    fi
    
    ./tmenv ./kccachetest sanity $THREADS 10000
    
    for thds in $(seq $THREADS); do 
    	for rep in $(seq $REPS); do
	    (taskset -c 0-7 \
		./tmenv \
		ocperf.py stat -x:: -e rtm_retired.start -e rtm_retired.commit -e rtm_retired.aborted "-e rtm_retired.aborted_misc"{1,2,3,4,5} \
		./kccachetest wicked -th $thds $RNUM 2>&1;
		echo 'algo:' $algo) >> $OUT
	done
    done 
done
